import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List, Dict, Optional, List
class EmailError(Exception):
    """Custom exception for email errors"""
    pass

class NewsEmailer:
    """Sends formatted news summaries via email"""
    
    def __init__(
        self,
        smtp_server: Optional[str] = None,
        smtp_port: Optional[int] = None,
        email: Optional[str] = None,
        password: Optional[str] = None
    ):
        self.smtp_server = smtp_server or os.getenv("SMTP_SERVER", "smtp.gmail.com")
        self.smtp_port = smtp_port or int(os.getenv("SMTP_PORT", "587"))
        self.email = email or os.getenv("SMTP_EMAIL")
        self.password = password or os.getenv("SMTP_PASSWORD")
        
        if not all([self.email, self.password]):
            raise ValueError("Email credentials not configured")
    
    def format_article_html(self, article_data: Dict) -> str:
        """Format a single article as HTML"""
        original = article_data["original"]
        summary = article_data["summary"]
        terms = article_data.get("terms", {})
        
        html = f"""
        <div style="margin-bottom: 30px; border-left: 3px solid #0066cc; padding-left: 15px;">
            <h2 style="color: #0066cc;">{original['title']}</h2>
            <p style="color: #666; font-size: 12px;">
                <strong>Source:</strong> {original['source']} | 
                <strong>Published:</strong> {original['published_at'][:10]}
            </p>
            
            <h3 style="color: #333;">📝 Summary</h3>
            <p style="line-height: 1.6;">{summary}</p>
            
            <p><a href="{original['url']}" style="color: #0066cc;">Read full article →</a></p>
        """
        
        if terms:
            html += """
            <h3 style="color: #333;">📚 Key Terms Explained</h3>
            <dl style="line-height: 1.8;">
            """
            for term, explanation in terms.items():
                html += f"""
                <dt style="font-weight: bold; color: #0066cc; margin-top: 10px;">{term}</dt>
                <dd style="margin-left: 20px;">{explanation}</dd>
                """
            html += "</dl>"
        
        html += "</div><hr style='border: none; border-top: 1px solid #eee;'>"
        
        return html
    
    def send_news_summary(
        self, 
        articles_data: List[Dict], 
        recipient: str,
        topic: str
    ) -> bool:
        """
        Send formatted news summary email
        
        Args:
            articles_data: List of processed article dictionaries
            recipient: Email address to send to
            topic: News topic/query
        
        Returns:
            True if successful, False otherwise
        """
        try:
            # Create message
            msg = MIMEMultipart('alternative')
            msg['Subject'] = f"📰 AI News Summary: {topic}"
            msg['From'] = self.email
            msg['To'] = recipient
            
            # Build HTML body
            html_body = f"""
            <html>
            <head>
                <style>
                    body {{ font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }}
                    h1 {{ color: #0066cc; }}
                </style>
            </head>
            <body>
                <h1>🤖 AI News Intelligence Agent</h1>
                <p style="color: #666;">Your personalized news summary for: <strong>{topic}</strong></p>
                <p style="color: #666;">Generated {len(articles_data)} article summaries</p>
                <hr style="border: none; border-top: 2px solid #0066cc; margin: 20px 0;">
            """
            
            for article_data in articles_data:
                html_body += self.format_article_html(article_data)
            
            html_body += """
                <hr style="border: none; border-top: 2px solid #0066cc; margin: 20px 0;">
                <p style="color: #999; font-size: 12px; text-align: center;">
                    Generated by AI News Intelligence Agent
                </p>
            </body>
            </html>
            """
            
            # Attach HTML
            html_part = MIMEText(html_body, 'html')
            msg.attach(html_part)
            
            # Send email
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.email, self.password)
                server.send_message(msg)
            
            return True
            
        except Exception as e:
            raise EmailError(f"Failed to send email: {str(e)}")